export const SET_FORM_IS_VALID = 'SET_FORM_IS_VALID';
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const SET_LOADING = 'SET_LOADING';
export const SET_REQUEST_RESPONSE = 'SET_REQUEST_RESPONSE';
export const SET_REQUEST_ERROR = 'SET_REQUEST_ERROR';
